# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # pick ONE of the stacks below (Node/Python/Java/etc.)
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # cache deps (speeds up builds)
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

      - run: npm ci
      - run: npm test --if-present
      - run: npm run build --if-present

      # keep build outputs for later jobs / debugging
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: |
            dist
            coverage
