name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'npm'  # Built-in caching, simpler than manual cache setup
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint --if-present
      
      - name: Run type checking
        run: npm run type-check --if-present
      
      - name: Run tests
        run: npm test --if-present
      
      - name: Build project
        run: npm run build --if-present
      
      # Upload test coverage to codecov or similar
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: success() && hashFiles('coverage/**') != ''
        with:
          directory: ./coverage
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            dist
            build
            coverage
          retention-days: 7
